ticketBooking/busTicketBooking/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    # path('<int:bus_id>/', views.seat, name='seat'),
    path('seat_status/', views.seat_status, name='seat_status'),
    path('seat_booking/', views.seat_booking, name='seat_booking'),
    # path('thanks/', views.thanks, name='thanks'),
    # path('api/get_station/', views.get_station, name='get_station'),
    path('seat_booking/sms-status/', views.sms_status, name='sms_status'),
    path('seat_booking/success/', views.success, name='success'),
    path('seat_booking/validate_payment/', views.validate_payment, name='validate_payment'),
]

ticketBooking/ticketBooking/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('busTicketBooking/', include('busTicketBooking.urls')),
    path('admin/', admin.site.urls),
]

ticketBooking/busTicketBooking/models.py
from django.db import models
from datetime import datetime
from phonenumber_field.modelfields import PhoneNumberField


class Bus(models.Model):
    OPERATOR_CHOICES = [
        ('Hanif', 'Hanif'),
        ('Green Line', 'Green Line'),
        ('Tungipara Express', 'Tungipara Express'),
        ('Saintmartin Hyundai', 'Saintmartin Hyundai')
    ]
    operator_name = models.CharField(max_length=50, choices=OPERATOR_CHOICES, default='...')

    MANUFACTURER_CHOICES = [
        ('SCANIA', 'Scania'),
        ('VOLVO', 'Volvo'),
        ('HYUNDAI', 'Hyundai'),
        ('HINO', 'Hino'),
        ('MAN', 'Man')
    ]
    manufacturer = models.CharField(max_length=50, choices=MANUFACTURER_CHOICES, default='HINO')

    CLASS_CHOICES = [
        ('ECONOMY', 'Economy Class'),
        ('BUSINESS', 'Business Class')
    ]
    Class = models.CharField(max_length=10, choices=CLASS_CHOICES, default='ECONOMY')

    hasAc = models.BooleanField(default=True)
    total_seat = models.IntegerField(default=40)
    num_of_rows = models.IntegerField(default=10)
    num_of_columns = models.IntegerField(default=4)
    column_in_first_row = models.IntegerField(default=4)
    column_in_last_row = models.IntegerField(default=5)

    def get_rows(self):
        rows = "ABCDEFGHI"
        if self.num_of_rows == 10:
            rows = rows + "J"
        return rows

    def natural_key(self):
        return (self.operator_name, self.manufacturer, self.hasAc, self.total_seat, self.num_of_rows,
                self.num_of_columns, self.column_in_first_row, self.column_in_last_row)

    def __str__(self):
        ret = self.operator_name + ' ' + self.manufacturer + ' '
        extra_information = 'AC' if self.hasAc is True else 'Non AC'
        ret = ret + extra_information + ' '
        extra_information = '(E)' if self.Class == 'ECONOMY' else '(B)'
        return ret + extra_information


class Seat(models.Model):
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE, null=True, blank=True)
    seat_no = models.CharField(max_length=50, default="A1")

    def __str__(self):
        ret = self.bus.operator_name + ' ' + self.bus.manufacturer + ' '
        extra_information = 'AC' if self.bus.hasAc is True else 'Non AC'
        ret = ret + extra_information + ' '
        extra_information = '(E)' if self.bus.Class == 'ECONOMY' else '(B)'
        return ret + extra_information + ' ' + self.seat_no


class Trip(models.Model):
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE, null=True, blank=True)
    coach_no = models.IntegerField(default=100)
    START_STATION_CHOICES = [
        ('DHAKA', 'Dhaka'),
        ('CHATTAGRAM', 'Chattagram'),
        ('BARISAL', 'Barisal'),
        ('SYLHET', 'Sylhet'),
        ('KHULNA', 'Khulna'),
    ]
    start_station = models.CharField(max_length=50, choices=START_STATION_CHOICES, default='...')

    DESTINATION_CHOICES = [
        ('DHAKA', 'Dhaka'),
        ('CHATTAGRAM', 'Chattagram'),
        ('BARISAL', 'Barisal'),
        ('SYLHET', 'Sylhet'),
        ('KHULNA', 'Khulna'),
    ]
    destination = models.CharField(max_length=50, choices=DESTINATION_CHOICES, default='...')

    fare = models.IntegerField(default=0)
    start_time = models.DateTimeField(default=datetime.now)
    end_time = models.TimeField(null=True, blank=True)
    description = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        ret = str(self.id) + ' ' + self.start_station + '-' + self.destination + ' '
        ret = ret + '(' + self.bus.operator_name + ')' + ' '
        return ret + self.start_time.strftime("%B %d, %Y %H:%M")


class TripSeat(models.Model):
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    seat_no = models.CharField(max_length=50)

    SEAT_STATUS_CHOICES = [
        ('AVAILABLE', 'Available'),
        ('SOLD', 'Sold'),
        ('BOOKED', 'Booked'),
        ('DISABLED', 'Disabled'),
    ]
    status = models.CharField(max_length=50, choices=SEAT_STATUS_CHOICES, default='...')

    def natural_key(self):
        return(self.trip.id, self.seat_no, self.status)

    def __str__(self):
        return str(self.trip) + ' ' + str(self.seat_no) + ' ' + self.status


class Passenger(models.Model):
    name = models.CharField(max_length=20)

    GENDER_CHOICES = [
        ('MALE', 'M'),
        ('FEMALE', 'F'),
        ('OTHER', 'O'),
    ]
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)

    mobile = PhoneNumberField(null=False, blank=False, region="BD")
    email = models.EmailField(max_length=50)


class Reservation(models.Model):
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    passenger = models.ForeignKey(Passenger, on_delete=models.CASCADE)
    reservation_time = models.DateTimeField(default=datetime.now)
    num_of_booked_seat = models.IntegerField(default=1)
    total_fare = models.IntegerField(default=0)


class ReservationSeat(models.Model):
    reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE)
    seat_no = models.CharField(max_length=10)


class Payment(models.Model):
    reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE)
    payment_status = models.CharField(max_length=20)  # VALID/ VALIDATED/ INVALID_TRANSACTION
    transaction_id = models.CharField(max_length=50, unique=True)
    total_amount = models.IntegerField(default=0)
    session_key = models.CharField(max_length=50, unique=True)
    card_brand = models.CharField(max_length=30)  # visa/ mobile banking
    card_type = models.CharField(max_length=50)  # bkash/ dutch bangla back/ city bank
    card_no = models.IntegerField(default=0)  # debit/ credit card number

ticketBooking/busTicketBooking/forms.py
from django.forms import ModelForm
from django import forms
from busTicketBooking.models import Passenger


class NameForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)


class PassengerInformation(ModelForm):
    class Meta:
        model = Passenger
        fields = ['name', 'gender', 'mobile', 'email']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Enter name'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Enter email'}),
            'mobile': forms.NumberInput(attrs={'placeholder': 'Enter mobile no'})
        }


class SearchBus(forms.Form):
    start_station = forms.CharField(
        label='From',
        max_length=15,
        widget=forms.TextInput(
            attrs={'placeholder': 'From'}
        )
    )
    destination = forms.CharField(
        label='To',
        max_length=15,
        widget=forms.TextInput(
            attrs={'placeholder': 'To'}
        )
    )
    # date_of_journey = forms.DateField(
    #    label='Date of Journey',
    #    widget=forms.widgets.DateInput(
    #        attrs={'type': 'date'}
    #    )
    # )
    date_of_journey = forms.CharField(
        label='Date of Journey',
        max_length=15,
        widget=forms.TextInput(
            attrs={'placeholder': 'Pick a date'}
        )
    )

ticketBooking/busTicketBooking/templates/busTicketBooking/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'busTicketBooking/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'busTicketBooking/home.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'busTicketBooking/footer.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- jQuery !-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        {% comment %}<script src="{% static 'busTicketBooking/bootstrap/js/bootstrap.min.js' %}"></script>{% endcomment %}
        <!-- jQuery UI !-->
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

        <link href="http://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="{% static 'busTicketBooking/jquery_seat/css/jquery.seat-charts.css' %}">
        <script src="{% static 'busTicketBooking/bootstrap/js/bootstrap.min.js' %}"></script>
        <title>{% block title %}{% endblock title %}</title>

        <style type="text/css">
            {% block css%}
            {% endblock css %}
        </style>

    </head>
    <body {% comment %}style="background-image: url({% static 'busTicketBooking/images/bus.jpg' %});"{% endcomment %}>

        <!-- Here add nav -->
        {% include "busTicketBooking/nav.html" %}

        {% block content %}{% endblock %}

        <!-- Here add footer -->
        {% comment %}{% include "busTicketBooking/footer.html" %}{% endcomment %}

    </body>
</html>

ticketBooking/busTicketBooking/templates/busTicketBooking/footer.html
<div class="footer navbar-fixed-bottom">
    Copyright@Arifur Rahman Sujon&Nusrat Jahan Pinky<br>
    <div class="wrapper">
      <a target="_blank" href="nusratjahan1535@gmail.com"><i class="fa fa-3x fa-google-plus"></i></a>
      <a target="_blank" href="https://www.facebook.com/arifurrahman.sujon.3"><i class="fa fa-3x fa-facebook-square"></i></a>
      <a target="_blank" href=""><i class="fa fa-3x fa-twitter-square"></i></a>
      <a target="_blank" href="https://www.linkedin.com/in/nusrat-jahan-30049a153/"><i class="fa fa-3x fa-linkedin-square" ></i></a>
      <a target="_blank" href=""><i class="fa fa-3x fa-github-square"></i></a>
    </div>
  </div>
</div>

ticketBooking/busTicketBooking/templates/busTicketBooking/home.html
{% extends "busTicketBooking/base.html" %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block css %}
    .container {
         background-image: url({% static 'busTicketBooking/images/bus.jpg' %});
    }
{% endblock css %}

{% block content %}

<div class="container" >
    <div class="row">
        <div class="col-sm-6 containertext">
            <span style="font-weight: bold;">Welcome to</span><br>
            Bus<br>
            E-Ticketing<br>
            Service<br>
        </div>
        <div class="col-sm-6 containerform">
            <form  autocomplete="off" action="{% url 'home' %}" method="get">
                {% csrf_token %}
                {% for field in form %}
                    <div class="fieldWrapper">
                        {{ field.errors }}
                        <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                        {{ field }}
                    </div>
                {% endfor %}
                <input type="submit" name="SearchBus" value="Search Buses"><br>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">

    $(function() {
        var station_list = [
            'Dhaka',
            'Khulna',
            'Chattagram',
            'Barisal',
            'Sylhet'
        ];
        $("#id_start_station, #id_destination").autocomplete({
            {% comment %}source: "{% url 'get_station' %}"{% endcomment %}
            source: station_list.sort()
        });
    });

    var date = new Date();
    var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
    var futureDate = new Date(date.getFullYear(), date.getMonth() + 2, date.getDate());

    $('#id_date_of_journey').datepicker({
        format: 'yyyy/mm/dd',
        minDate: today,
        maxDate: futureDate
    });

</script>

{% endblock content %}

ticketBooking/busTicketBooking/templates/busTicketBooking/name.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'get_name' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
</form>
</body>
</html>

ticketBooking/busTicketBooking/templates/busTicketBooking/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" style="width: 100%; position: fixed; top: 0px; overflow:hidden;">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
        <a class="navbar-brand" href="#" style="color: darkorange; font-weight: bold;">Online Ticket Booking</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="#"><span class="glyphicon glyphicon-home"></span> Home</a></li>
                <li><a href="#">Cancel Ticket</a></li>
                <li><a href="#">Bus Reservation</a></li>
                <li><a href="#">Verify Ticket</a></li>
                <li><a href="#"> Contact Us</a></li>
            </ul>
        </div>
    </div>
</nav>

ticketBooking/busTicketBooking/templates/busTicketBooking/seat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .button {
          padding: 15px 25px;
          font-size: 24px;
          text-align: center;
          cursor: pointer;
          outline: none;
          color: #fff;
          background-color: #4CAF50;
          border: none;
          border-radius: 15px;
          box-shadow: 0 9px #999;
        }

        .button:hover {background-color: #3e8e41}

        .button:active {
          background-color: #3e8e41;
          box-shadow: 0 5px #666;
          transform: translateY(4px);
        }
    </style>
</head>
<body>
<p>num of rows: {{ seat.num_of_rows }}</p>
<ul style="list-style-type:none;">
  <li>
      <ul style="list-style-type:none; float: left;">
          <li><button class="button">{{ seat.A1 }}</button></li><br>
          <li><button class="button">{{ seat.A2 }}</button></li><br>
          <li><button class="button">{{ seat.A3 }}</button></li><br>
          <li><button class="button">{{ seat.A4 }}</button></li>
      </ul>
  </li>

</ul>
<p id = "demo">click</p>
<script>
    document.getElementById("demo").innerHTML = "Hello JavaScript!";
</script>
</body>
</html>

ticketBooking/busTicketBooking/templates/busTicketBooking/seat_booking.html
{% extends "busTicketBooking/base.html" %}
{% load static %}

{% block title %}Seat Booking{% endblock title %}

{% block css%}
{%endblock css %}
<style type="text/css">

    {% comment %}.container{
        margin
    }{% endcomment %}
    #passenger-info {
        background-color: green;
        color: white;
        width: auto;
        height: 30px;
        line-height: 30px;
        padding-left: 10px;
        font-weight: bold;
    }

    #id_name, #id_gender, #id_mobile, #id_email{
        width: 100%;
        padding: 5px 10px;
        margin: 1px 0;
        box-sizing: border-box;
        color: #000000;
    }

    .contain-form{
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0, 0.4);
        border:1px solid rgba(0,0,0,0.1);
        border-bottom-left-radius:3px;
        border-bottom-right-radius:3px;
        color: white;
        padding-top: 10px;
        padding-bottom: 12px;
    }

</style>

{% block content %}
<script>
    let seatList = {{ seat_list|safe }};
    function printSeatList() {
        let element = document.getElementById("seat-no");
        for(let i = 0; i < seatList.length; i++) {
           element.innerText += seatList[i];
           if(i < seatList.length - 1)element.innerText += ','
        }
    }
</script>
<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div id="passenger-info">Passenger Information</div>
                <div class="contain-form">
                    <form id="passenger-info-form" action="{% url 'seat_booking' %}"  method="post"  onsubmit="addInfo()">
                        {% csrf_token %}
                        {{ form.non_field_errors}}
                        {% for field in form.visible_fields %}
                            <div class="fieldWrapper">
                                {{ field.errors }}
                                <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                                {{ field }}
                            </div>
                        {% endfor %}
                    </form>
                </div>
            </div>
            <div class="col-md-6 text-center" >
                <h3>Journey Details</h3>
                <h4>{{ trip.start_station }}-{{ trip.destination }}</h4><br>
                {{ trip.bus.operator_name }}<br>
                {{ trip.start_time}}<br>
                <span id="seat-no">Seat No(s):</span>
                <script>
                    printSeatList();
                </script>
                <br>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
           <div class="col-md-6">
               <!--<div class="align-middle" id="payment">Fare Details</div>-->
               <table id="fare-table" class="table table-condensed">
                    <thead>
                       <tr style="background-color: green; color: white;">
                           <th>Fare Details</th>
                           <th>Amount (TK)</th>
                       </tr>
                   </thead>
                   <tbody>
                       <tr>
                           <td>
                               Ticket Price
                           </td>
                           <td>
                               {{ total_fare }}
                           </td>
                       </tr>
                        <tr class="active">
                           <td>
                               Website Fee
                           </td>
                           <td id="website-fee">
                           </td>
                           <script>
                               $('#website-fee').text(seatList.length * 10);
                           </script>
                       </tr>
                       <tr>
                           <td>
                               Processing Fee
                           </td>
                           <td id="processing-fee">
                           </td>
                           <script>
                               $('#processing-fee').text(seatList.length * 5);
                           </script>
                       </tr>
                       <tr class="active">
                           <td>
                               Total
                           </td>
                           <td id="total-amount" style="font-size: 18px; color: red;">
                           </td>
                           <script>
                               let websiteFee = $('#website-fee').text();
                               let processingFee = $('#processing-fee').text();
                               let otherFee = parseInt(websiteFee.toString()) + parseInt(processingFee.toString());
                               let totalFee = {{ total_fare }} + otherFee;
                               $('#total-amount').text(totalFee);
                           </script>
                       </tr>
                   </tbody>
               </table>
           </div>
        </div>
        <div style="text-align: center;">
        <input type="submit" style="color:white; width: 400px; background-color: #fc1408; border-style: outset;" id="Confirm" value="Confirm Reservation" onclick="addInfo()">
        </div>
    </div>
</div>
<script>
function  addInfo() {
    let form = document.getElementById("passenger-info-form");

    // seat list
    var hiddenField = document.createElement('input');
    hiddenField.type = 'hidden';
    hiddenField.name = 'seat_list';
    hiddenField.value = JSON.stringify(seatList);
    form.appendChild(hiddenField);

    // fare
    var hiddenField = document.createElement('input');
    hiddenField.type = 'hidden';
    hiddenField.name = 'total_fare';
    hiddenField.value = '{{ total_fare }}';
    form.appendChild(hiddenField);

     // payable fee
    var hiddenField = document.createElement('input');
    hiddenField.type = 'hidden';
    hiddenField.name = 'total_payable_fee';
    hiddenField.value = $('#total-amount').text().toString();
    form.appendChild(hiddenField);

    // trip
    hiddenField = document.createElement('input');
    hiddenField.type = 'hidden';
    hiddenField.name = 'trip_id';
    hiddenField.value = '{{ trip.id }}';
    form.appendChild(hiddenField);

    submitForm();
}
function submitForm() {
    let form = document.getElementById("passenger-info-form");
    form.submit();
}
</script>
{% endblock content %}

ticketBooking/busTicketBooking/templates/busTicketBooking/seat_plan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ticketBooking/busTicketBooking/templates/busTicketBooking/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
success
</body>
</html>

ticketBooking/busTicketBooking/templates/busTicketBooking/thanks.html
{% comment %}
{% extends "busTicketBooking/base.html" %}
{% load static %}
{% block title %}Home{% endblock title %}

{% block css %}

{% endblock css %}


<!DOCTYPE html>
<html>
<head></head>
<body>
{% for trip in trip_list %}
    <p>
        start: {{ trip.start_station }} des: {{ trip.destination }} date: {{ trip.start_time }} faka seat: {{ trip.seat }}
    </p>
{% endfor %}
</body>

<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<style>

#seat-row li {
  display:inline;
  list-style-type:none;
}
#seat li {
    //display:inline;
    list-style-type:none;
}
.button {
    background-color: #ffffff;
    border: 2px solid #101210;
    padding: 15px 15px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}
p {
    border: 1px solid gray;
    background-color: #e4e7ed;
    color: #0f0f0f;
}
</style>
</head>

<body>
<script>
    var seatInfo = JSON.parse("{{ seat_info|escapejs }}");
    //var tripList =JSON.parse("{{ trip_list|escapejs }}");
    //var str = JSON.stringify(tripList, null, 4); // (Optional) beautiful indented output.
    //console.log(str); // Logs output to dev tools console.
    var cnt = {};
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip({
            trigger : 'hover'
        });
    });

    function myFunction(id) {
        // if 4 seats have been chosen and it is new seat no more seat can be selected
        var table = document.getElementById("selected-seat");
        if(table.rows.length == 5 && cnt[id] == 1) {
            alert("You have already booked 4 seats");
            return;
        }

        changeColor(id);

        // we only add row if it is new and total selected seats is less than 4
        // if it is new its color will be change. so now cnt[id] = 0
        if(table.rows.length < 5 && cnt[id] == 0)addRow(id, {{ trip.fare }});
        else {
            // we can deselect previously selected row
            for(var i = 1; i < table.rows.length; i++) {
                if(table.rows[i].cells[0].innerHTML == id) {
                    table.deleteRow(i);
                    break;
                }
            }
        }
        document.getElementById("total-fare").innerText = "Total Fare: " + (table.rows.length -1) * {{ trip.fare }} + " Taka";
    }
    function changeColor(id) {
        var element = document.getElementById(id);
        if(cnt[id] == 1) {
            element.style.backgroundColor = "#09eb20";// green
            cnt[id] = 0;
        }
        else {
            element.style.backgroundColor = "#ffffff";// white
            cnt[id] = 1;
        }
    }

    function setColor(id, seatType) {
        cnt[id] = 1;// 1 means available
                    // 0 means you select it
        var color;
        var element = document.getElementById(id);
        element.title = id ;
        switch (seatType) {
            case 'AVAILABLE':
                color = "#ffffff";
                element.addEventListener("click", function() {
                    myFunction(id);
                    /*// if 4 seats have been chosen no more seat can be selected
                    if(document.getElementById("selected-seat").rows.length < 5) {
                        myFunction(id);
                    }*/
                });
                break;
            case 'BOOKED':
                color = "#e9f542";
                break;
            case 'SOLD':
                color = "#d90804";
                break;
            case 'DISABLED':
                color = "#59504f";
                break;
            default:
                color = "#000000";
        }
        element.style.backgroundColor = color;
    }
    function addRow(content, morecontent)
    {
         if (!document.getElementsByTagName) return;
         tabBody=document.getElementsByTagName("tbody").item(0);
         row=document.createElement("tr");
         cell1 = document.createElement("td");
         cell2 = document.createElement("td");
         textnode1=document.createTextNode(content);
         textnode2=document.createTextNode(morecontent);
         cell1.appendChild(textnode1);
         cell2.appendChild(textnode2);
         row.appendChild(cell1);
         row.appendChild(cell2);
         tabBody.appendChild(row);
    }

    function postToView( method='post') {
        var params = {};

        var table = document.getElementById("selected-seat");
        for(var i = 1; i < table.rows.length; i++) {
            params["seat" + i] = table.rows[i].cells[0].innerHTML;
        }

        const form = document.createElement('form');
        form.method = method;
        form.action = "{% url 'get_name' %}";
        for (const key in params) {
            if (params.hasOwnProperty(key)) {
                const hiddenField = document.createElement('input');
                hiddenField.type = 'hidden';
                hiddenField.name = key;
                hiddenField.value = params[key];
                form.appendChild(hiddenField);
            }
        }
        // trip
        var hiddenField = document.createElement('input');
        hiddenField.type = 'hidden';
        hiddenField.name = 'trip_id';
        hiddenField.value = '{{ trip.id }}';
        form.appendChild(hiddenField);
        // csrf
        hiddenField = document.createElement('input');
        hiddenField.type = 'hidden';
        hiddenField.name = 'csrfmiddlewaretoken';
        hiddenField.value = '{{ csrf_token }}'
        form.appendChild(hiddenField);
        document.body.appendChild(form);
        form.submit();
    }

</script>
<div class="container-fluid">

    <div class="col-sm-4" style="margin-top: 20px">
        <ul id="seat">
            {% for row in "ABCDEFGHIJ" %}
                <li>
                    <ul id="seat-row">
                        {% if trip.bus.num_of_columns == 4 %}
                            {% for col in "1234" %}
                                <li><button data-toggle="tooltip" data-placement="top" id="{{ row|add:col }}" class="button"></button>
                                <script>
                                    id = "{{ row|add:col }}";
                                    setColor(id, seatInfo[id]);
                                </script>
                                </li>
                            {% endfor %}
                        {% else %}
                            {% for col in "123" %}
                                <li><button data-toggle="tooltip" data-placement="top" id="{{ row|add:col }}" class="button"></button>
                                <script>
                                    id = "{{ row|add:col }}";
                                    setColor(id, seatInfo[id]);
                                </script>
                                </li>
                            {% endfor %}
                        {% endif %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-sm-4" style="margin-top: 20px">
        <table class="table" id="selected-seat">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Seats</th>
                    <th scope="col">Fare</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
        <p id="total-fare">Total Fare: 0 Taka</p>
        <button id="save" class="button" onclick="postToView()"></button>

    </div>
</div>

</body>
</html>
{% endcomment %}